sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t bhuwanbhasker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhuwanbhasker/react-test npm test

after_success:
  - docker build -t bhuwanbhasker/multi-client ./client
  - docker build -t bhuwanbhasker/multi-nginx ./nginx
  - docker build -t bhuwanbhasker/multi-api ./api
  - docker build -t bhuwanbhasker/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push image to docker hu
  - docker push bhuwanbhasker/multi-client
  - docker push bhuwanbhasker/multi-nginx
  - docker push bhuwanbhasker/multi-api
  - docker push bhuwanbhasker/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-app-aws
  env: DockerAppAws-env
  bucket_name: elasticbeanstalk-us-east-2-551180489795
  bucket_path: docker-app-aws
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY