sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t bhuwanbhasker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t bhuwanbhasker/multi-client ./client
  - docker build -t bhuwanbhasker/multi-nginx ./nginx
  - docker build -t bhuwanbhasker/multi-api ./api
  - docker build -t bhuwanbhasker/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push image to docker hub
  - docker push bhuwanbhasker/multi-client
  - docker push bhuwanbhasker/multi-nginx
  - docker push bhuwanbhasker/multi-api
  - docker push bhuwanbhasker/multi-worker
